### ISSUE TITLE
Lists and multidrivers get duplicated when other users open a slot

### ISSUE THREAD

**Issue by Krzeszny** [art0007i/MyInspectors#18]
This doesn't happen when the mod's user opens it, but happens if others do it
<img width="1154" height="615" alt="Image" src="https://github.com/user-attachments/assets/ec967861-b730-4b28-8c2f-026924d03dd1" />

**Comment by BlueTera** [comment]
> If it happens try to get everyone who has the mod to disable it, then enable it again. let me know if it fixes it or not.
That's not really a fix it still happens

**Comment by EIA485** [comment]
im unable to re-create this issue. what other mods/loaders are you using?

**Comment by Krzeszny** [comment]
> im unable to re-create this issue. what other mods/loaders are you using?

0 other mods. It's perfectly reproducible for me as long as I have MyInspectors **enabled** and someone else doesn't.

**Comment by art0007i** [comment]
with the latest release this should be fixed. let me know if it's not then I can reopen

**Comment by Krzeszny** [comment]
It's still happening. Sometimes for me, sometimes for a friend, but not always, and it's on a headless. For example, two of us have this mod and we're on a headless. It's happening for one of us, but not for the other one.

**Comment by EIA485** [comment]
sounds like someone is not running the latest version

**Comment by Krzeszny** [comment]
@art0007i It's happening again with me running version 2.1.1. Slots get visually doubled in the default inspector, as well as their components. I was in a session with 1 user, the host, who had no mods, and in another session with a host who had mods, but not this mod.

It only happens when I'm not a host. It happens once in a few opened slots (say, once in 10), or sometimes every time.

Do you want a log from the normal version?
